title: "Hector Cid del prado Soto"
logo: assets/foto_perfil.png
description: "🚀 ¡Bienvenido! Aquí muestro mis proyectos más relevantes en análisis de datos, aplicando herramientas como Python, SQL, Power BI y Tableau. Soy una persona entusiasta, extrovertida y con facilidad para trabajar en equipo. Me apasiona aprender de manera autodidacta y estoy listo para enfrentar nuevos retos."  
theme: jekyll-theme-minimal
show_downloads: false
github: 
    is_project_page: false

